---
groups:
- name: stats
  jobs:
  - fetch
  - process
  - display
- name: create
  jobs: 
  - build
  - sanity-test
  - bump-version
  - deployment

resources:
- name: deploy-repo
  type: git
  source:
    uri: git@github.com:PXMYH/ci.git
    branch: master
    private_key: ((github_secret_key))

- name: web_app
  type: git
  source:
    uri: git@github.com:PXMYH/web_app.git
    branch: master
    private_key: ((github_secret_key))
    
- name: get-smoke-test
  type: docker-image
  source:
    repository: cfcloudops/cf-smoke-tests
    username: ((docker_hub_username))
    password: ((docker_hub_password))

- name: every-30-min
  type: time
  source: {interval: 30m}

- name: version
  type: semver
  source:
    initial_version: 0.0.0
    driver: git
    uri: git@github.com:PXMYH/web_app.git
    branch: master
    # file name to be saved with version
    file: version_file
    private_key: ((github_secret_key))

jobs:
- name: fetch
  serial: true
  plan:
  - get: every-30-min
  - get: deploy-repo
    trigger: true
  - task: fetch_db
    file: deploy-repo/tasks/fetch_db.yml

- name: process
  serial: true
  plan:
  - get: deploy-repo
    passed: [fetch]
    trigger: true
  - task: process_info
    file: deploy-repo/tasks/process_info.yml

- name: display
  serial: true
  plan:
  - get: deploy-repo
    passed: [fetch, process]
  - task: display
    file: deploy-repo/tasks/display.yml

- name: build
  public: true
  serial: true
  plan:
  - get: web_app
    trigger: true
  - task: build
    params: 
    file: web_app/ci/tasks/browse.yml
  
- name: bump-version
  public: true
  serial: true
  plan:
  - get: web_app
    passed: [build, sanity-test]
  - get: version
    params: {bump: patch}
  - put: version
    # 'number' is the where semver saves version number to, but not a file, the actual file is defined in resource file variable
    params: {file: version/number} 

# run Ginkgo framework sanity test suites
- name: sanity-test
  public: true
  plan:
  - get: web_app
    trigger: true
    passed: [build]
  - task: get-sanity-test
    file: web_app/ci/tasks/get-sanity-test-suites.yml

# run cloud foundry smoke test suites
- name: smoke-test
  public: true
  plan:
  - get: every-30-min
    trigger: true
  - get: get-smoke-test
    trigger: true
  - task: run-smoke-test
    file: web_app/ci/tasks/get-smoke-test-suites.yml

# deploy to S3 bucket
- name: deployment
  public: true
  serial: true
  plan:
  - get: web_app
    trigger: true
    passed: [sanity-test, bump-version]
