---
groups:
- name: create
  jobs: 
  - build
  - sanity-test
  - bump-version
  - deployment

resources:
- name: get-repo
  type: git
  source:
    uri: git@github.com:PXMYH/web_app.git
    branch: master
    private_key: ((github_secret_key))

- name: version
  type: semver
  source:
    initial_version: 0.0.0
    driver: git
    uri: git@github.com:PXMYH/web_app.git
    branch: master
    # file name to be saved with version
    file: version_file
    private_key: ((github_secret_key))

jobs:
- name: build
  public: true
  serial: true
  plan:
  - get: get-repo
    trigger: true
  - task: build
    file: web_app/ci/tasks/browse.yml
  
  
- name: bump-version
  public: true
  serial: true
  plan:
  - get: get-repo
  - get: version
    params: {bump: patch}
  - put: version
    # 'number' is the where semver saves version number to, but not a file, the actual file is defined in resource file variable
    params: {file: version/number} 

- name: sanity-test
  public: true
  serial: true
  plan:
  - get: get-repo
    trigger: true

- name: deployment
  public: true
  serial: true
  plan:
  - get: get-repo
    trigger: true
