---
platform: linux

image_resource:

  type: docker-image

  source:
      repository: alpine
      tag: latest

inputs: 
- name: deploy-repo

run:
  path:  deploy-repo/kubecon/scripts/deploy-concourse.sh