version: '3'

services:

  consul:
    image: consul
    container_name: kubecon-consul
    hostname: consul
    command: "agent -dev -client 0.0.0.0"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"

  vault:
    image: vault
    container_name: kubecon-vault
    hostname: vault
    depends_on:
      - consul
    links:
      - "consul:consul"
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
    ports:
      - "8200:8200"
    volumes:
      - "./tools/wait-for-it.sh:/wait-for-it.sh"
      - "./config/vault:/config"
      - "./config/vault/policies:/policies"
    entrypoint: /wait-for-it.sh -t 20 -h consul -p 8500 -s -- vault server -config=/config/with-consul.hcl

  concourse-db:
    image: postgres:9.6
    container_name: kubecon-db
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: ${postgres_username}
      POSTGRES_PASSWORD: ${postgres_password}
      PGDATA: /database

  concourse-web:
    image: concourse/concourse
    container_name: kubecon-web
    command: web --vault-insecure-skip-verify
    links: 
      - concourse-db
    depends_on: 
      - vault
      - concourse-db
    ports: 
      - "8080:8080"
    volumes: 
      - "./keys/web:/concourse-keys"
    restart: unless-stopped # required so that it retries until concourse-db comes up
    environment:
      CONCOURSE_BASIC_AUTH_USERNAME: ${concourse_main_username}
      CONCOURSE_BASIC_AUTH_PASSWORD: ${concourse_main_password}
      CONCOURSE_EXTERNAL_URL: ${concourse_server_ip}
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: ${postgres_username}
      CONCOURSE_POSTGRES_PASSWORD: ${postgres_password}
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_VAULT_URL: http://vault:8200
      CONCOURSE_VAULT_PATH_PREFIX: /concourse
      CONCOURSE_VAULT_CLIENT_TOKEN: ${vault_fake_token}
      CONCOURSE_VAULT_INSECURE_SKIP_VERIFY: "true"

  concourse-worker:
    image: concourse/concourse
    container_name: kubecon-worker
    command: worker
    privileged: true
    links: 
      - concourse-web
    depends_on:
      - concourse-web
    volumes:
      - "./keys/worker:/concourse-keys"
    restart: always
    environment:
      CONCOURSE_TSA_HOST: concourse-web
