---
groups:
- name: deploy-kube
  jobs:
  - prepare
  - deploy

resources:
- name: deploy-repo
  type: git
  source:
    uri: git@github.com:PXMYH/ci.git
    branch: master
    private_key: ((github_secret_key))

jobs:
- name: prepare
  serial: true
  plan:
  - get: deploy-repo
    trigger: true
  - task: prep-kube-image
    file: deploy-repo/tasks/prep_kube_image.yml