---
groups:
- name: stats
  jobs:
  - fetch
  - process
  - display

- name: create
  jobs: 
  - build
  - sanity-test
  - bump-version
  - deployment
  - smoke-test

- name: factory
  jobs:
  - get-aws-cli
  - get-cf-cli
  - compile-hermes

- name: deploy-kube
  jobs:
  - prepare
  - deploy

resource_types:
- name: hashicorp-release
  type: docker-image
  source:
    repository: starkandwayne/hashicorp-release-resource

resources:
- name: deploy-repo
  type: git
  source:
    uri: git@github.com:PXMYH/ci.git
    branch: master
    private_key: ((github_secret_key))

- name: web_app
  type: git
  source:
    uri: git@github.com:PXMYH/web_app.git
    branch: master
    private_key: ((github_secret_key))
    
- name: get-smoke-test
  type: docker-image
  source:
    repository: cfcloudops/cf-smoke-tests
    username: ((dockerhub_username))
    password: ((dockerhub_password))

- name: every-30-min
  type: time
  source: {interval: 30m}

- name: version
  type: semver
  source:
    initial_version: 0.0.0
    driver: git
    uri: git@github.com:PXMYH/web_app.git
    branch: master
    # file name to be saved with version
    file: version_file
    private_key: ((github_secret_key))

- name: hermes-docker-tag
  type: semver
  source:
    initial_version: 0.0.0
    driver: s3
    key: docker/docker-tag
    bucket:            ((output_bucket_name))
    access_key_id:     ((aws_access_key_id))
    secret_access_key: ((aws_secret_access_key))
    region_name: us-east-2

- name: hermes-docker
  type: docker-image
  source:
    username:   ((dockerhub_username))
    password:   ((dockerhub_password))
    repository: coeus77/hermes

- name: terraform-release
  type: hashicorp-release
  source:
    project: terraform

- name: vault-release
  type: hashicorp-release
  source:
    project: vault

- name: consul-release
  type: hashicorp-release
  source:
    project: consul

- name: jq-github-release
  type: github-release
  source:
    owner: stedolan
    repository: jq
    access_token: ((github_access_token)) # Avoids rate limits

- name: concourse-github-release
  type: github-release
  source:
    owner: concourse
    repository: concourse
    access_token: ((github_access_token)) # Avoids rate limits

- name: spruce-github-release
  type: github-release
  source:
    owner: geofffranks
    repository: spruce
    access_token: ((github_access_token)) # Avoids rate limits

- name: cf-cli-github-release
  type: github-release
  source:
    owner: cloudfoundry
    repository: cli
    access_token: ((github_access_token)) # Avoids rate limits

- name: cf-cli-s3-release
  type: s3
  source:
    versioned_file: cf/cf
    bucket: ((output_bucket_name))
    access_key_id: ((aws_access_key_id))
    secret_access_key: ((aws_secret_access_key))
    region_name: us-east-2

- name: bosh-s3-release
  type: s3
  source:
    bucket: bosh-cli-artifacts
    regexp: 'bosh-cli-(2\.\d+(\.\d+)?)-linux-amd64'

- name: yaml-github-release
  type: github-release
  source:
    owner: mikefarah
    repository: yq
    access_token: ((github_access_token)) # Avoids rate limits

- name: base-image
  type: docker-image
  source:
    repository: alpine

- name: aws-cli-git
  type: git
  source:
    uri: https://github.com/aws/aws-cli.git
    tag_filter: 1.*.*
- name: aws-cli-s3-release
  type: s3
  source:
    versioned_file: pipelines/aws-cli/awscli-bundle.zip
    bucket: ((output_bucket_name))
    access_key_id: ((aws_access_key_id))
    secret_access_key: ((aws_secret_access_key))
    region_name: us-east-2

- name: credhub-cli-github-release
  type: github-release
  source:
    owner: cloudfoundry-incubator
    repository: credhub-cli
    access_token: ((github_access_token)) # Avoids rate limits

- name: certstrap-github-release
  type: github-release
  source:
    owner: square
    repository: certstrap
    access_token: ((github_access_token))

jobs:
- name: fetch
  serial: true
  plan:
  - get: every-30-min
  - get: deploy-repo
    trigger: true
  - task: fetch_db
    file: deploy-repo/tasks/fetch_db.yml

- name: process
  serial: true
  plan:
  - get: deploy-repo
    passed: [fetch]
    trigger: true
  - task: process_info
    file: deploy-repo/tasks/process_info.yml

- name: display
  serial: true
  plan:
  - get: deploy-repo
    passed: [process]
    trigger: true
  - task: display
    file: deploy-repo/tasks/display.yml

- name: build
  serial: true
  plan:
  - get: web_app
    trigger: true
  - task: build
    params: 
    file: web_app/ci/tasks/browse.yml
  
- name: bump-version
  serial: true
  plan:
  - get: web_app
    passed: [build, sanity-test]
  - get: version
    params: {bump: patch}
  - put: version
    # 'number' is the where semver saves version number to, but not a file, the actual file is defined in resource file variable
    params: {file: version/number} 

# run Ginkgo framework sanity test suites
- name: sanity-test
  plan:
  - get: web_app
    trigger: true
    passed: [build]
  - task: get-sanity-test
    file: web_app/ci/tasks/get-sanity-test-suites.yml

# run cloud foundry smoke test suites
- name: smoke-test
  plan:
  - get: every-30-min
    trigger: true
  - get: get-smoke-test
    trigger: true
  - task: run-smoke-test
    file: web_app/ci/tasks/get-smoke-test-suites.yml

# deploy to S3 bucket
- name: deployment
  serial: true
  plan:
  - get: web_app
    trigger: true
    passed: [sanity-test, bump-version]


# Following jobs are for building base docker images

- name: get-cf-cli
  public: true
  serial: true
  plan:
  - get: cf-cli-github-release
    trigger: true
  - task: download
    config:
      platform: linux
      inputs:
      - name: cf-cli-github-release
      outputs:
      - name: cf
      image_resource:
        type: docker-image
        source: {repository: busybox}
      run:
        path: ash
        args:
        - -c
        - |
          set -euo pipefail
          version=$(cat cf-cli-github-release/version)
          url="https://cli.run.pivotal.io/stable?release=linux64-binary&version=${version}&source=github-rel"
          wget --output cli.tgz "$url"
          tar -C cf -xzf cli.tgz
  - put: cf-cli-s3-release
    params: {file: cf/cf}

- name: get-aws-cli
  serial: true
  plan:
  - get: aws-cli-git
    trigger: true
  - task: download
    config:
      platform: linux
      outputs:
      - name: aws-cli
      image_resource:
        type: docker-image
        source: {repository: busybox}
      run:
        path: ash
        args:
        - -c
        - |
          set -euo pipefail
          url="https://s3.amazonaws.com/aws-cli/awscli-bundle.zip"
          wget --output aws-cli/awscli-bundle.zip "$url"
  - put: aws-cli-s3-release
    params: {file: aws-cli/awscli-bundle.zip}

- name: compile-hermes
  serial: true
  plan:
  - aggregate:
    - get: hermes-docker-tag
      params: 
        bump: patch
    # Download Dockerfile
    - get: deploy-repo
      trigger: true
    # Trigger on base image updates
    - get: base-image
      trigger: true
    # Download dependancies
    - get: cf-cli-s3-release
      trigger: true
      passed: [get-cf-cli]
    - get: terraform-release
      trigger: true
      params:
        regexp: linux_amd64
    - get: vault-release
      trigger: true
      params:
        regexp: linux_amd64
    - get: consul-release
      trigger: true
      params:
        regexp: linux_amd64
    - get: jq-github-release
      trigger: true
      params:
        globs: [jq-linux64]
    - get: concourse-github-release
      trigger: true
      params:
        globs: [fly_linux_amd64]
    - get: spruce-github-release
      trigger: true
      params:
        globs: [spruce-linux-amd64]
    - get: bosh-s3-release
      trigger: true
    - get: yaml-github-release
      trigger: true
      params:
        globs: [yq_linux_amd64]
    - get: aws-cli-s3-release
      trigger: true
      passed: [get-aws-cli]
    - get: credhub-cli-github-release
      trigger: true
      params:
        globs: [credhub-linux-*.tgz]
    - get: certstrap-github-release
      trigger: true
      params:
        globs: [certstrap-v*-linux-amd64]
  # Copy dependencies
  - task: copy
    file: deploy-repo/tasks/copy.yml

  - put: hermes-docker
    params:
      build: builddir
      tag: hermes-docker-tag/version
      tag_as_latest: true
  
  - task: hermes-sanity-test
    file: deploy-repo/tasks/hermes_sanity_test.yml

  - put: hermes-docker-tag
    params: 
      file: hermes-docker-tag/version
      bump: patch


- name: prepare
  serial: true
  plan:
  - get: deploy-repo
    trigger: true
  - task: prep-kube-image
    file: deploy-repo/tasks/prep_kube_image.yml
    params:
      HOST_IP: ((host_ip))
      HOST_PRIVATE_KEY: |
        ((host_private_key))

- name: deploy
  serial: true
  plan:
  - get: deploy-repo
    trigger: true
    passed:
    - prepare
  - task: deploy-kube-image
    file: deploy-repo/tasks/deploy_kube_image.yml
    params:
      HOST_IP: ((host_ip))
      HOST_PRIVATE_KEY: |
        ((host_private_key))